server:
  port: 8088


spring:
  data:
    mongodb:
      uri: mongodb://springcloudRoot:springcloudRoot@127.0.0.1:27017/springcloud

#      database: springcloud
#      host: 127.0.0.1
#      port: 27017
#      username: springcloudRoot
#      password: springcloudRoot

logging:                            # 配置 spring 的日志输出，对业务日志无效
  
  file:                             # 配置日志保存位置
    # path: ./log                     # 将 spring 的日志保存到指定路径
    # name: spring.log                # 保存到指定路径下的指定文件
    max-size:  10MB                 # 日志文件最大 10 MB，超过自动新建一个文件
    max-history: 7                  # 最多保存几个日志文件
    clean-history-on-start: true    # 重起时自动清空所有日志文件
  
  
  group:                            # 配置日志组，用于统一配置
    tomcat: org.apache.catalina, org.apache.coyote, org.apache.tomcat
  
  level:
    root: warn
    org:
      springframework:
        web: debug                  # 针对单个日志记录器配置日志级别
    tomcat: warn                    # 针对日志组，配置日志级别
    sql: debug
  
  exception-conversion-word: LogException  # 日志本身出错
