server:
  port: 8088

  tomcat:
    uri-encoding: utf-8
  
 
logging:                            # 配置 spring 的日志输出，对业务日志无效

  file:                             # 配置日志保存位置
    # path: ./log                     # 将 spring 的日志保存到指定路径
    # name: spring.log                # 保存到指定路径下的指定文件
    max-size:  10MB                 # 日志文件最大 10 MB，超过自动新建一个文件
    max-history: 7                  # 最多保存几个日志文件
    clean-history-on-start: true    # 重起时自动清空所有日志文件
    
    
  group:                            # 配置日志组，用于统一配置
    tomcat: org.apache.catalina, org.apache.coyote, org.apache.tomcat
    
  level:
    root: warn
    org:
      springframework:
        web: debug                  # 针对单个日志记录器配置日志级别
    tomcat: warn                    # 针对日志组，配置日志级别
    sql: debug

  exception-conversion-word: log exception  # 日志本身出错


spring:

  messages:                         # spring 系统消息 i18n 配置
    basename: messages,config.i18n.messages
    encoding: utf-8
    fallback-to-system-locale: false

  main:
    lazy-initialization: false

  application:
    admin:
      enabled: false  # 开启之后，可以远程管理 spring boot 应用

  mvc:
    favicon:
      enabled: false
    contentnegotiation:             # spring boot 内容协商
      favor-parameter: true         # 开启内容类型协商参数
      parameter-name: format        # 用于内容类型协商的参数名
      media-types:
        markdown: text/markdown     # 自定义扩展内容类型

  datasource:
    primary:
      jdbc-url: jdbc:oracle:thin:@//10.63.29.99:1521/BPM12CTS
      username: bpm_issue
      password: 1234
      driver-class-name: oracle.jdbc.OracleDriver
    slaver:
      jdbc-url: jdbc:mysql://192.168.1.12:3306/kasei?characterEncoding=utf8&allowMultiQueries=true&serverTimezone=UTC
      username: kasei
      password: kasei
      driver-class-name: com.mysql.cj.jdbc.Driver
    redis:
      server: 127.0.0.1
      port: 6379
    
#    neo4j:
#      url: bolt://localhost:7687
#      username: neo4j
#      password: root
#      connection:
#        pool:
#          size: 150
    h2:
      jdbc-url: jdbc:h2:file:E:/Git/GitLocalRepository/SpringBoot/src/main/resources/h2         # 使用本地文件作为数据库
      #jdbc-url: jdbc:h2:mem:testdb              # 使用内存数据库，项目关闭则数据丢失
      username: kasei
      password: kasei
      driver-class-name: org.h2.Driver
  data:
    neo4j:
      uri: file:///opt/Git/LocalRepository/SpringBoot/src/main/resources/embededdatabase/neo4j/graph.db
    mongodb:
      uri: mongodb://springcloudRoot:springcloudRoot@127.0.0.1:27017/springcloud
  h2:
    console:
      enabled: true
      path: /h2
#  kafka:
#    admin:
#      client-id:
#    bootstrap-servers:

