server:
  port: 8088
  tomcat:
    uri-encoding: utf-8


spring:
  security:
    user:
      password: kasei
      name: kasei
      roles:
        - root
  data:
    mongodb:
      host: "127.0.0.1"
      port: 27017
      database: "springcloud"
      username: "springcloudRoot"
      password: "LogCenterAdmin"
