

server:
  port: 8088
  tomcat:
    uri-encoding: utf-8

logging:
  level:
    root: debug

spring:
  security:
    user:
      password: kasei
      name: kasei
      roles:
        - root
  datasource:
    driver-class-name: org.h2.Driver
    # 该 url 表示使用的是本地文件数据库，IFEXISTS=TRUE 表示数据库存在时才打开，否则报错
    # TRACE_LEVEL_SYSTEM_OUT=3        表示日志输出到 System.out 且日志级别为 3 DEBUG, 2 INFO, 1 ERROR, 0 OFF
    # TRACE_LEVEL_FILE=0              表示日志输出到文件
    url: "\
     jdbc:h2:file:./Web/src/main/resources/embededdatabase/h2/db1\
     ;TRACE_LEVEL_FILE=0\
     ;TRACE_LEVEL_SYSTEM_OUT=3\
     ;MODE=MySQL\
     ;DATABASE_TO_LOWER=TRUE;PAGE_SIZE=2048\
     ;IFEXISTS=TRUE\
     "
    
    # 该格式的 url 表示创建的是内存数据库
    # url: jdbc:h2:mem:MyDatabaseName
    username: root
    password: root
    platform: h2
    # schema: classpath:embededdatabase/h2/schema.sql   # 只适用于首次创建数据库
    # data: classpath:embededdatabase/h2/data.sql       # 只适用于首次创建数据库
    

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
    show-sql: true
    database: h2
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
        trace: false
